version: 2.1

# Incluir el orb de Slack
orbs:
  slack: circleci/slack@4.9.3

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Dar permisos y ejecutar script
          command: |
            chmod +x script.sh
            ./script.sh

  test:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas
          command: |
            apt-get update && apt-get install -y bats
            bats ./tests/test.bats

  # Job de notificación con Slack usando el orb
  notify_slack:
    docker:
      - image: cimg/base:current
    steps:
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*Pipeline ejecutado con éxito* 🚀",
                      "emoji": true
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Proyecto*: pruebatecnica VirtualSoft siii"
                    }
                  ]
                }
              ]
            }
          event: always

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - notify_slack:
          requires:
            - test
          context: slack-secrets  # Usar el contexto que contiene la variable 'SLACK_WEBHOOK_URL'
