version: 2.1
jobs:
  execute-script:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Execute Bash Script
          command: |
            #!/bin/bash
            ./script.sh
workflows:
  version: 2
  execute:
    jobs:
      - execute-script
