version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Dar permisos y ejecutar script
          command: |
            chmod +x script.sh
            ./script.sh

  test:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: Ejecutar pruebas
          command: |
            apt-get update && apt-get install -y bats
            bats ./tests/test.bats

  notify_slack:
    docker:
      - image: curlimages/curl:latest
    steps:
      - run:
          name: Enviar notificación a Slack
          command: |
            curl -X POST -H 'Content-type: application/json' --data '{
              "text": "✅ *Pipeline ejecutado con éxito* 🚀\n_Proyecto_: pruebatecnica VirtualSoft siii"
            }' "https://hooks.slack.com/services/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"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - notify_slack:
          requires:
            - test
