name: Revisar syntax del README 
on:
  pull_request:
    branches:
      - develop
jobs:
  check_syntax:
    runs-on: ubuntu-latest
    steps:
    - name: Revisar repositorio el archivo .md
    - uses: actions/checkout@v4
    - uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        globs: |
          *.md
          !test/*.md


