name: Revisar syntax del README 
on:
  pull_request:
    branches:
      - develop
jobs:
  check_syntax:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Instalamos libreria para revsiar nuestro ReadMe
      run: |
        npm install -g markdownlint-cli
    - name: Corremos markdownlint en nuetro README
      run: markdownlint README.md

